# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calorie-Awareness' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calorie-Awareness

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

  target 'Calorie-AwarenessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Calorie-AwarenessUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
